# Generated by Django 6.0.5 on 2026-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('TAE', 'TAE'), ('Diretor', 'Diretor'), ('Gestor', 'Gestor')], max_length=20)),
                ('foto', models.ImageField(upload_to='rostos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
