# Generated by Django 6.0.5 on 2026-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
